blogs/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('my_blogs.urls')),
    path('members/', include('django.contrib.auth.urls')),
    path('members/', include('members.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)


admin.site.site_header = "i-Blogger Adminstration"
admin.site.site_title = "i-Blogger"
admin.site.index_title = "i-Blogger Admin Pannel"

# video no 28

my_blogs/urls.py
from django.urls import path
from . import views
from .views import Home, BlogDetail, AddPost, UpdatePost, DeletePost, AddCategory, CategoryView, CategoryList, LikesOnPost, AddComment

urlpatterns = [
    # path('', views.index, name="home"),
    path('', Home.as_view(), name="home"),
    path('article/<int:pk>', BlogDetail.as_view(), name="article"),
    path('add_blogs/', AddPost.as_view(), name="add_blogs"),
    path('add_category/', AddCategory.as_view(), name="add_category"),
    path('article/edit/<int:pk>', UpdatePost.as_view(), name="Edit-Blogs"),
    path('article/<int:pk>/remove', DeletePost.as_view(), name="delete"),
    path('category/<str:catg>/', CategoryView, name="category"),
    path('category-list/', CategoryList, name="category-list"),
    path('like/<int:pk>', LikesOnPost, name="like_post"),
    path('article/<int:pk>/comment/', AddComment.as_view(), name="add_comment"),


]
# video no. 25

my_blogs/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse
from datetime import datetime, date
from ckeditor.fields import RichTextField


class Post(models.Model):
	title = models.CharField(max_length=200)
	title_tag = models.CharField(max_length=200)
	author = models.ForeignKey(User, on_delete=models.CASCADE)
	# content = models.TextField()
	image = models.ImageField(null=True, blank=True, upload_to="images/")
	content = RichTextField(blank=True, null=True)
	created_on = models.DateField(auto_now_add=True)
	category = models.CharField(max_length=200, default='coding')
	snippets = models.CharField(max_length=200)
	likes = models.ManyToManyField(User, related_name='blog_posts')

	class Meta:
		ordering = ['-created_on']

	def total_likes(self):
		return self.likes.count()

	def __str__(self):
		return self.title + ' | ' + str(self.author)

	def get_absolute_url(self):
		return reverse('home')

class Category(models.Model):
	name = models.CharField(max_length=200)

	def __str__(self):
		return self.name

	def get_absolute_url(self):
		return reverse('home')

class UserProfile(models.Model):
	user = models.OneToOneField(User, null=True, on_delete=models.CASCADE)
	bio = models.TextField()
	profile_pic = models.ImageField(null=True, blank=True)
	web_url = models.CharField(max_length=200, null=True, blank=True)
	fb_url = models.CharField(max_length=200, null=True, blank=True)
	instagram_url = models.CharField(max_length=200, null=True, blank=True)
	linkedin_url = models.CharField(max_length=200, null=True, blank=True)
	whatsapp_url = models.CharField(max_length=200, null=True, blank=True)


	def __str__(self):
		return str(self.user)

	def get_absolute_url(self):
		return reverse('home')

class Comment(models.Model):
	post = models.ForeignKey(Post, related_name="comments", on_delete=models.CASCADE)
	name = models.CharField(max_length=200)
	body = models.TextField()
	date_added = models.DateTimeField(auto_now_add=True)

	class Meta:
		ordering = ['-date_added']
	

	def __str__(self):
		return '%s - %s' % (self.post.title, self.name)
		

my_blogs/forms.py
from django import forms
from .models import Post, Category, Comment

# choices = [('coding', 'coding'), ('sports', 'sports'), ('news', 'news')]

choices = Category.objects.all().values_list('name', 'name')

choice_list = []

for item in choices:
    choice_list.append(item)



class PostForm(forms.ModelForm):
    class Meta:
        model = Post        
        fields = ('title', 'title_tag', 'author', 'image', 'category', 'content', 'snippets')
        widgets = {
        'title': forms.TextInput(attrs={'class': 'form-control'}),
        'title_tag': forms.TextInput(attrs={'class': 'form-control'}),
        'author': forms.TextInput(attrs={'class': 'form-control', 'value': '', 'id': 'elder', 'type': 'hidden'}),
        # 'author': forms.Select(attrs={'class': 'form-control'}),
        'category': forms.Select(choices=choice_list, attrs={'class': 'form-control'}),
        'content': forms.Textarea(attrs={'class': 'form-control'}),
        'snippets': forms.Textarea(attrs={'class': 'form-control'}),
        }

class EditForm(forms.ModelForm):
    class Meta:
        model = Post        
        fields = ('title', 'title_tag','category', 'content', 'snippets')
        widgets = {
        'title': forms.TextInput(attrs={'class': 'form-control'}),
        'title_tag': forms.TextInput(attrs={'class': 'form-control'}),
        'category': forms.Select(choices=choice_list, attrs={'class': 'form-control'}),
        'content': forms.Textarea(attrs={'class': 'form-control'}),
        'snippets': forms.Textarea(attrs={'class': 'form-control'}),
        }

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment        
        fields = ('name', 'body')
        widgets = {
        'title': forms.TextInput(attrs={'class': 'form-control'}),
        'body': forms.Textarea(attrs={'class': 'form-control'}),
        }

my_blogs/views.py
from django.shortcuts import render, get_object_or_404
from django.views.generic import CreateView, ListView, DetailView, UpdateView, DeleteView
from .models import Post, Category, Comment
from .forms import PostForm, EditForm, CommentForm
from django.urls import reverse_lazy, reverse
from django.http import HttpResponseRedirect, HttpResponse


# def index(request):
# 	return render(request, 'index.html', {})

class Home(ListView):
	model = Post
	template_name = 'index.html'
	# ordering = ['-created_on']
	ordering = ['-id']

	def get_context_data(self, *args,**kwargs):
		catg_menu = Category.objects.all()
		context = super(Home, self).get_context_data(*args, **kwargs)
		context["catg_menu"] = catg_menu
		return context


def CategoryView(request, catg):
	category_posts = Post.objects.filter(category=catg)
	ordering = ['-created_on']
	return render(request, 'category.html', {'catg': catg.title().replace('-', ' '), 'category_posts': category_posts})

	
class BlogDetail(DetailView):
	model = Post
	template_name = 'blog_detail.html'

	def get_context_data(self, *args,**kwargs):
		catg_menu = Category.objects.all()
		context = super(BlogDetail, self).get_context_data(*args, **kwargs)
		stuff = get_object_or_404(Post, id=self.kwargs['pk'])

		total_likes = stuff.total_likes()
		liked = False
		if stuff.likes.filter(id=self.request.user.id).exists():
			liked = True

		context["catg_menu"] = catg_menu
		context["total_likes"] = total_likes
		context["liked"] = liked
		return context

class AddPost(CreateView):
	model = Post
	form_class = PostForm
	template_name = 'add_blogs.html'
	# fields = '__all__'
	# fields = ['title', 'title_tag', 'author', 'content']

class AddComment(CreateView):
	model = Comment
	form_class = CommentForm
	template_name = 'add_comment.html'
	# fields = '__all__'
	ordering = ['-date_added']


	def form_valid(self, form):
		form.instance.post_id = self.kwargs['pk']
		return super().form_valid(form)

	success_url = reverse_lazy('home')
	
	

class UpdatePost(UpdateView):
	model = Post
	template_name = 'edit.html'
	form_class = EditForm
	# fields = ['title', 'title_tag', 'content']

class DeletePost(DeleteView):
	model = Post
	template_name = 'delete.html'
	success_url = reverse_lazy('home')

class AddCategory(CreateView):
	model = Category
	# form_class = PostForm
	template_name = 'add_category.html'
	fields = '__all__'

def CategoryList(request):
	category_menu = Category.objects.all()
	ordering = ['-created_on']
	return render(request, 'category_list.html', {'category_menu': category_menu})

def LikesOnPost(request, pk):
	post = get_object_or_404(Post, id=request.POST.get('post_id'))
	liked = False
	if post.likes.filter(id=request.user.id).exists():
		post.likes.remove(request.user)
		liked = False
	else:
		post.likes.add(request.user)
		liked = True
	
	return HttpResponseRedirect(reverse('article', args=[str(pk)]))

my_blogs/templates/add_blogs.html
{% extends 'base.html' %}
{% block title %}Create Blog{% endblock %}

{% block content %}


{% if user.is_authenticated %}
	<h2>Write Your Blog...</h2>
	<br>
	{# <div class=""> #}
	<div class="form-group">
		<form method="POST" enctype="multipart/form-data">
			{% csrf_token %}
			{{ form.media }}
			{{ form.as_p }}
			<button class="btn btn-primary">Post</button>
		</form>
	</div>
	<script>
	var name = "{{ user.id }}";
	document.getElementById('elder').value = name;
	</script>

{% else %}
ERROR 404! - Forbidden<br>
Page Not Found
{% endif %}
{% endblock %}

my_blogs/templates/add_category.html
{% extends 'base.html' %}
{% block title %}Create Category{% endblock %}

{% block content %}


{% if user.is_authenticated %}
	<h2>Add Category...</h2>
	<br>
	{# <div class=""> #}
	<div class="form-group">
		<form method="POST">
			{% csrf_token %}
			{{ form.as_p }}
			<button class="btn btn-primary">Add Category</button>

			<a href="{% url 'home' %}" class="btn btn-secondary">Back</a>
		</form>
	</div>
{% else %}
ERROR 404! - Forbidden<br>
Page Not Found
{% endif %}
{% endblock %}

my_blogs/templates/add_comment.html
{% extends 'base.html' %}
{% block title %}Comment{% endblock %}

{% block content %}


	<section style="background-color: #eee;">
	  	<div class="container my-5 py-5 text-dark">
	    	<div class="row d-flex justify-content-center">
	      		<div class="col-md-10 col-lg-8 col-xl-6">
	          		<form method="POST">
						{% csrf_token %}
	        			<div class="card">
	          				<div class="card-body p-4">
	    						<center><i><h1 class="mb-3">Comments...</h1></i></center>
		            			<div class="d-flex flex-start w-100">
		              				<img class="rounded-circle shadow-1-strong me-3 mr-3" src="https://mdbcdn.b-cdn.net/img/Photos/Avatars/img%20(25).webp" alt="avatar" width="65" height="65">
		              				<div class="w-100">
		              					<div class="form-outline flex-fill mb-4">
											<input type="text" name="name" autofocus autocapitalize="none" autocomplete="username" maxlength="150" required id="id_name" class="form-control" placeholder="Name">
										</div>
		            					<div class="form-outline mt-4">
		            						<textarea name="body" cols="40" rows="10" class="form-control" placeholder="+ Add a Comment" required id="id_body"></textarea>
		                				</div>
		                				<div class="d-flex justify-content-between mt-3">
		                  					<button class="btn btn-primary">Post</button>
		                				</div>
		              				</div>
		            			</div>
	          				</div>
	        			</div>
		            </form>
	      		</div>
	    	</div>
	  	</div>
	</section>

	<script>
		var name = "{{ user.id }}";
		document.getElementById('elder').value = name;
	</script>


{% endblock %}

my_blogs/templates/base.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel = "icon" href="media/1.png" type="image/x-icon">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css" integrity="sha384-xOolHFLEh07PJGoPkLv1IbcEPTNtaed2xpHsD9ESMhqIYd0nLMwNLD69Npy4HI+N" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.9.1/font/bootstrap-icons.css">

    <title> i-Blogger | {% block title %}{% endblock %}</title>
  </head>
  <body>

    <!-- navbar starts here-->
    <nav class="navbar sticky-top navbar-expand-lg navbar-dark bg-dark">
      <a class="navbar-brand" href="{% url 'home' %}">i-Blogger</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        
        <ul class="navbar-nav mr-auto">
          {% if catg_menu %}
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-expanded="false">
                Category</a>
              <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                {% for items in catg_menu %}
                  <a class="dropdown-item" href="{% url 'category' items %}">{{ items }}</a>
                {% endfor %}
                <div class="dropdown-divider"></div>
                <a class="dropdown-item " href="{% url 'category-list' %}">All Categories</a>
              </div>
            </li>
          {% else %} 
          
          {% endif %}
          
        </ul>

        {% if user.is_authenticated %}
          


          <ul class="navbar-nav ml-auto">
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-expanded="false">
                Hello, {{ user.username}}
              </a>
              <ul class="dropdown-menu">
                {% if user.userprofile.id %}
                  <li><a class="dropdown-item" href="{% url 'profile' user.userprofile.id %}">My Profile</a></li>
                  <li><a class="dropdown-item" href="#">My Blogs</a></li>
                  {% if user.is_superuser %}
                  <li><a class="dropdown-item" href="/admin/">Admin</a></li>
                  {% endif %}
                {% else %}
                  <li><a class="dropdown-item" href="{% url 'create_profile' %}">Create Profile</a></li>
                {% endif %}
                <li><hr class="dropdown-divider"></li>
                <li><a class="dropdown-item" href="{% url 'edit_settings' %}">Settings</a></li>
              </ul>
            </li>
            <li class="nav-item active">
              <a class="nav-link mx-2" href="{% url 'add_blogs' %}"><i class="bi bi-plus"></i> Write Blogs</a>
            </li>   
          </ul>          
          <a href="{% url 'logout' %}" class="btn btn-outline-danger">Sign Out</a>
        {% else %}
          <ul class="navbar-nav ml-auto">
            <a href="{% url 'login' %}" class="btn btn-outline-primary mx-3">Sign In</a>
          </ul>
        {% endif %}
      </div>
    </nav> 
    <!-- navbar ends here -->


    <br>
    <div class="container">
      {% block content %}

      {% endblock %}
    </div>
    <script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-Fy6S3B9q64WdZWQUiU+q4/2Lc9npb8tCaSX9FK7E8HnRr0Jz8D6OP9dO5Vg3Q9ct" crossorigin="anonymous"></script>

    <!-- Option 2: Separate Popper and Bootstrap JS -->
    <!--
    <script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/js/bootstrap.min.js" integrity="sha384-+sLIOodYLS7CIrQpBjl+C7nPvqq+FbNUBDunl/OZv93DB7Ln/533i8e/mZXLi/P+" crossorigin="anonymous"></script>
    -->
    
  </body>

  <footer class="bg-dark text-center text-white">
    <!-- Grid container -->
    <div class="container p-4 pb-0">
      <!-- Section: Social media -->
      <section class="mb-4">

        <!-- Email -->
        <a class="btn text-white btn-floating m-1" style="background-color: #0f80af;" href="mailto: mukundjitiwari@gmail.com" target="_blank" role="button">
          <i class="bi bi-envelope-open"></i
        ></a>

        <!-- Whats App -->
        <a class="btn text-white btn-floating m-1" style="background-color: #008000;" href="https://wa.me/+919451721374" target="_blank" role="button">
          <i class="bi bi-whatsapp"></i
        ></a>

        <!-- Instagram -->
        <a class="btn text-white btn-floating m-1" style="background-color: #C13584;" href="https://www.instagram.com/tiwariji_05" target="_blank" role="button">
          <i class="bi bi-instagram"></i
        ></a>

        <!-- Linkedin -->
        <a class="btn text-white btn-floating m-1" style="background-color: #0082ca;" href="https://www.linkedin.com/in/mukund-jee-tiwari/" target="_blank" role="button">
          <i class="bi bi-linkedin"></i>
        </a>

        <!-- Github -->
        <a class="btn text-white btn-floating m-1" style="background-color: #333333;" href="https://github.com/tiwariji-mukund" target="_blank" role="button">
          <i class="bi bi-github"></i
        ></a>

      </section>
      <!-- Section: Social media -->
    </div>
    <!-- Grid container -->

    <!-- Copyright -->
    <div class="text-center p-3" style="background-color: rgba(0, 0, 0, 0.2);">
      © 2022 Copyright:
      <a class="text-white" href="{% url 'home' %}">i-Blogger.com</a><br>
    </div>
    <!-- Copyright -->
  </footer>
  
</html>

my_blogs/templates/blog_detail.html
{% extends 'base.html' %}
{% load static %}
{% block title %}{{post.title}}{% endblock %}
{% block content %}
	<nav aria-label="breadcrumb">
	  <ol class="breadcrumb">
	    <li class="breadcrumb-item">{{ post.created_on }}</li>
	    <li class="breadcrumb-item active" aria-current="page">#{{ post.title_tag }}</li>
	  </ol>
	</nav>

	<h1 class="my-2">{{ post.title }}</h1><br>
	<small>
		<i class="bi bi-pen-fill mr-2"><a href="{% url 'profile_page' post.author.userprofile.id %}"> {{post.author.first_name}} {{post.author.last_name}} </a></i><i class="bi bi-tags-fill mr-2"><a href="{% url 'category' post.category %}"> {{post.category}} </a></i><i class="bi bi-calendar-date mr-3"> {{ post.created_on }}</i>
		{% if user.is_authenticated %}
			{% if user.id == post.author.id %}
				<a class="btn btn-primary btn-sm" href="{% url 'Edit-Blogs' post.pk %}"><i class="bi bi-pencil-square ml-2 mr-2">   Edit</i></a>
				<a class="btn btn-danger btn-sm" href="{% url 'delete' post.pk %}"><i class="bi bi-trash3-fill">  Delete</i></a>
			{% endif %}
		{% endif %}
	</small>
	<hr><br>
	{% if post.image %}
		<center>
			<img src="{{ post.image.url }}" height="400px" width="600px" class="rounded">
		</center><br><br>
	{% endif %}
	<div class="container mb-4" style="text-align: justify;">{{ post.content | safe }}</div><br><br>

	<!--Likes-->
	<center>
		<form action="{% url 'like_post' post.pk %}" method="POST" class="container mb-2 my-3">
			<i class="bi bi-hand-thumbs-up-fill"> Total Likes: {{ total_likes }}</i>
			{% csrf_token %}
			{% if user.is_authenticated %}
				{% if liked %}
					<button type="submit", name="post_id", value="{{ post.id }}", class="btn btn-danger btn-sm mx-2"><i class="bi bi-hand-thumbs-down"> Unlike</i></button>
				{% else %}
					<button type="submit", name="post_id", value="{{ post.id }}", class="btn btn-primary btn-sm mx-2"><i class="bi bi-hand-thumbs-up"> Like</i></button>
				{% endif %}
			{% else %}
				<small><a href="{% url 'login' %}">Login</a> to like this Blog.</small>
			{% endif %}
		</form>
	</center>
	
	
	

	<!-- Comment Section -->
	<div class="row d-flex justify-content-center mt-4 my-2">
  		<div class="col-md-8 col-lg-6">
    		<div class="card shadow-0 border" style="background-color: #f0f2f5;">
      			<div class="card-body p-4">
        			<div class="form-outline mb-4">
        				<!--
				        <input type="text" id="addANote" class="form-control" placeholder="Type comment..." />
				    	-->
				        <label class="form-label mt-3" for="addANote"><a href="{% url 'add_comment' post.pk %}">+ Add a Comment...</a></label>
			        </div>
			        {% if not post.comments.all %}
						<div class="card mb-4">
	          				<div class="card-body">
	            				<p>No Comments Yet...</p>
	          				</div>
		        		</div>
					{% else %}
						{% for comment in post.comments.all %}
					        <div class="card mb-4">
		          				<div class="card-body">
		            				<p>{{ comment.body }}</p>
		            				<div class="d-flex justify-content-between">
		              					<div class="d-flex flex-row align-items-center">
		                					<img src="https://mdbcdn.b-cdn.net/img/Photos/Avatars/img%20(4).webp" alt="avatar" width="25" height="25" />
		                					<p class="small mb-0 ml-2 ms-2">{{ comment.name }}</p>
		              					</div>
			              				<div class="d-flex flex-row align-items-center">
							                <p class="small text-muted mb-0">{{ comment.date_added }}</p>
							            </div>
		            				</div>
		          				</div>
			        		</div>
			        	{% endfor %}
					{% endif %}
	        	</div>
	        </div>
	    </div>
	</div>

	<!-- Profile -->
	<section class="vh-50">
		<div class="container py-5 h-50">
		    <div class="row d-flex justify-content-center align-items-center h-50">
			    <div class="col col-md-9 col-lg-7 col-xl-5">
			        <div class="card" style="border-radius: 15px;">
			          	<div class="card-body p-4">
			            	<div class="d-flex text-black">
			              		<div class="flex-shrink-0 mr-3">
			              			<a href="{% url 'profile_page' post.author.userprofile.id %}">
								    	{% if post.author.userprofile.profile_pic %}
								      		<img src="{{ post.author.userprofile.profile_pic.url }}" alt="Generic placeholder image" class="img-fluid" style="width: 150px; height: 200px; border-radius: 10px;">
								      	{% else %}
								      		<img src="https://mdbcdn.b-cdn.net/img/Photos/new-templates/bootstrap-profiles/avatar-1.webp" alt="Generic placeholder image" class="img-fluid" style="width: 180px; border-radius: 10px;">
								    	{% endif %}
							    	</a>
			                	</div>
				              	<div class="flex-grow-1">
				                	<h3 class="mb-1">
				                		<a href="{% url 'profile_page' post.author.userprofile.id %}">{{post.author.first_name}} {{post.author.last_name}}</a></h3>
				                	<p class="mb-2 pb-1" style="color: #2b2a2a;">{{post.author.username}}</p>
				                	<div class="d-flex justify-content-center rounded-3" style="background-color: #efefef;">
					                  	<p class="small text-muted my-2">
								        	{% if post.author.userprofile.web_url %}
								        		<a href="{{ post.author.userprofile.web_url }}" target="_blank"><i class="bi bi-globe2 mr-3"></i></a>
								        	{% endif %} 
								        	{% if post.author.userprofile.fb_url %}
									        	<a href="{{ post.author.userprofile.fb_url }}" target="_blank"><i class="bi bi-facebook mr-3"></i></a>
									        {% endif %} 
									        {% if post.author.userprofile.instagram_url %}
									    		<a href="{{ post.author.userprofile.instagram_url }}" target="_blank"><i class="bi bi-instagram mr-3"></i></a>  
									    	{% endif %} 
									    	{% if post.author.userprofile.linkedin_url %}
									    		<a href="{{ post.author.userprofile.linkedin_url }}" target="_blank"><i class="bi bi-linkedin mr-3"></i></a> 
									    	{% endif %} 
									    	{% if post.author.userprofile.whatsapp_url %}
									    		<a href="{{ post.author.userprofile.whatsapp_url }}" target="_blank"><i class="bi bi-whatsapp mr-3"></i></a>
										    {% endif %} 
										</p>
				                	</div>
					                <div class="d-flex pt-1">
					                  	<a type="submit" href="{% url 'profile_page' post.author.userprofile.id %}" class="btn btn-primary mt-4 ml-auto"><i class="bi bi-eye-fill"></i> View</a>
                  						
					                </div>
				              	</div>
			            	</div>
			          	</div>
			        </div>
			    </div>
		    </div>
		</div>
	</section>
{% endblock %}

my_blogs/templates/category.html
{% extends 'base.html' %}
{% block title %}Category{% endblock %}
{% block content %}
	
	{% if category_posts %}
		<h1><b><u><i>{{ catg }}</i></u></b></h1><br>
			<!-- Card deck -->
			<div class="row row-cols-1 row-cols-md-3">
				{% for post in category_posts %}
			  		<div class="col mb-4">
				    	<!-- Card -->
				    	<div class="card">
					      	<!--Card image-->
				      		<div class="view overlay" height="200" width="200">
					    		<a href="{% url 'article' post.pk %}"><div class="mask rgba-white-slight"></div>
									{% if post.image %}
										<img src="{{ post.image.url }}" class="rounded" height="200" width="349" style="justify-content: center; display: flex;">
									{% else %}
										<img class="card-img-top" src="https://mdbootstrap.com/img/Photos/Others/images/16.webp" alt="Card image cap" class="rounded" height="200" width="349" style="justify-content: center; display: flex;">
									{% endif %}
					    		</a>
					  		</div>
					      	<!--Card content-->
					      	<div class="card-body">
						        	<!--Title-->
						        	<h4 class="card-title"><a href="{% url 'article' post.pk %}">{{post.title}}</a></h4>
					        		<small>
										<i class="bi bi-pen-fill mr-3 ml-1"><a href="{% url 'profile_page' post.author.userprofile.id %}" class="icon ml-2">{{post.author.first_name}} {{post.author.last_name}}</a></i><i class="bi bi-calendar-date ml-3 mr-2"></i>{{ post.created_on }}
									</small>							
						        	<!--Text-->
						        	<p class="card-text">{{ post.snippets }}</p>
						        	<!-- Provides extra visual weight and identifies the primary action in a set of buttons -->
						        	<a href="{% url 'article' post.pk %}" class="btn btn-outline-primary mr-auto">Read More</a>
					      	</div>
				    	</div>
			    		<!-- Card -->
			  		</div>
				{% endfor %}
			</div>
			<!-- Card deck -->
	{% else %}
		<h2>Error: Page Could Not Found!!!</h2>
	{% endif %}

{% endblock %}